"""empty message

Revision ID: 739874bc6d6e
Revises: 4b3be757eb2c
Create Date: 2024-08-02 20:53:14.245179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739874bc6d6e'
down_revision = '4b3be757eb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('charity', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
